### ISSUE TITLE
winbar

### ISSUE THREAD

**Issue by dualfade** [crivotz/nv-ide#20]
Guys, 
While looking for a new potential neovim ide replacement, I stumbled into your nv-ide. It looks very nice. very promising. I just wanted to make you aware of this ( winbar ) issue after installation --

Error detected while processing /home/dualfade/.nv-ide/plugin/packer_compiled.lua:
E355: Unknown option: winbar

Thank you.

**Comment by crivotz** [comment]
Thanks for the issue the problem is probably on the version of Neovim you are using.
The `winbar` should still be only in the `nightly` branch of Neovim (I use should because having been on vacation I haven't looked at the releases anymore)
So to fix the issue you can either use the `nightly` version of Neovim or the `neovim_stable` branch where I don't use features that are too new

**Comment by dualfade** [comment]
Got it. Appreciate the write back. I am running Archlinux / Blackarch.

local/neovim 0.7.2-3

No worries. I will investigate a little more now that I am vacation finally. 

be good.
~!>D
